import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Experience from "@/components/Experience";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import ContactMe from "@/components/ContactMe";
import HomeButton from "@/components/HomeButton";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div   id="Document" className="text-gray-500 h-screen bg-gradient-to-b from-stone-900 to-stone-950 z-0 overflow-x-hidden overflow-y-scroll scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/50 scrollbar-thumb-rounded-full scrollbar-track-rounded-full hover:scrollbar-thumb-[#F7AB0A] transition duration-300 ease-in-out"
       >
      <Head>
        <title>Marcos Freitas /* Web Developer */</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main      >
        {/* Header */}
        <Header />
        {/* Hero */}
        <section id="hero">
          <Hero />
        </section>
        {/* About */}
        <section id="about">
          <About />
        </section>
        {/* Experience */}
        <section id="experience">
          <Experience />
        </section>
        {/* Skills */}
        <section id="skills">
          <Skills />
        </section>
        {/* Projects */}
        <section id="projects">
          <Projects />
        </section>
        {/* Contact */}
        <section id="contact">
          <ContactMe />
        </section>
        {/* Home Button */}
        <HomeButton />
      </main>
    </div>
  );
}
